#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_
#undef IEEE802154_CONF_DEFAULT_CHANNEL
#define IEEE802154_CONF_DEFAULT_CHANNEL 23
#undef IEEE802154_CONF_PANID
#define IEEE802154_CONF_PANID 0xABD9
#define LOG_CONF_LEVEL_RPL LOG_LEVEL_DBG
#define LOG_CONF_LEVEL_TCPIP LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_6LOWPAN LOG_LEVEL_DBG
#define LOG_CONF_LEVEL_MAC LOG_LEVEL_DBG
#define LOG_CONF_LEVEL_FRAMER LOG_LEVEL_INFO
#define TSCH_LOG_CONF_PER_SLOT 0
#undef IEEE802154_CONF_DEFAULT_CHANNEL

#define IEEE802154_CONF_DEFAULT_CHANNEL 23
#undef IEEE802154_CONF_PANID
#define IEEE802154_CONF_PANID 0xABD9
//SECURITY
#define LLSEC802154_CONF_ENABLED 1
#define CSMA_CONF_LLSEC_SECURITY_LEVEL 3
#define CSMA_CONF_LLSEC_KEY_ID_MODE 1
#endif
